// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.iot_gamer.hand_landmarker

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object HandLandmarkerPluginPigeonUtils {
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class HandLandmarkerEventResult (
  val timestampMs: Long,
  val landmarks: List<HandLandmarkList>,
  val worldLandmarks: List<HandLandmarkList>,
  val handedness: List<HandLandmarkCategoryList>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HandLandmarkerEventResult {
      val timestampMs = pigeonVar_list[0] as Long
      val landmarks = pigeonVar_list[1] as List<HandLandmarkList>
      val worldLandmarks = pigeonVar_list[2] as List<HandLandmarkList>
      val handedness = pigeonVar_list[3] as List<HandLandmarkCategoryList>
      return HandLandmarkerEventResult(timestampMs, landmarks, worldLandmarks, handedness)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timestampMs,
      landmarks,
      worldLandmarks,
      handedness,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HandLandmarkerEventResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return HandLandmarkerPluginPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HandLandmarkList (
  val data: List<HandLandmark>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HandLandmarkList {
      val data = pigeonVar_list[0] as List<HandLandmark>
      return HandLandmarkList(data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HandLandmarkList) {
      return false
    }
    if (this === other) {
      return true
    }
    return HandLandmarkerPluginPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HandLandmarkCategoryList (
  val data: List<HandLandmarkCategory>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HandLandmarkCategoryList {
      val data = pigeonVar_list[0] as List<HandLandmarkCategory>
      return HandLandmarkCategoryList(data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HandLandmarkCategoryList) {
      return false
    }
    if (this === other) {
      return true
    }
    return HandLandmarkerPluginPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HandLandmark (
  val x: Double,
  val y: Double,
  val z: Double,
  val visibility: Double? = null,
  val presence: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HandLandmark {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      val z = pigeonVar_list[2] as Double
      val visibility = pigeonVar_list[3] as Double?
      val presence = pigeonVar_list[4] as Double?
      return HandLandmark(x, y, z, visibility, presence)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
      z,
      visibility,
      presence,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HandLandmark) {
      return false
    }
    if (this === other) {
      return true
    }
    return HandLandmarkerPluginPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HandLandmarkCategory (
  val score: Double,
  val index: Long,
  val categoryName: String,
  val displayName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HandLandmarkCategory {
      val score = pigeonVar_list[0] as Double
      val index = pigeonVar_list[1] as Long
      val categoryName = pigeonVar_list[2] as String
      val displayName = pigeonVar_list[3] as String
      return HandLandmarkCategory(score, index, categoryName, displayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      score,
      index,
      categoryName,
      displayName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HandLandmarkCategory) {
      return false
    }
    if (this === other) {
      return true
    }
    return HandLandmarkerPluginPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class HandLandmarkerPluginPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HandLandmarkerEventResult.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HandLandmarkList.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HandLandmarkCategoryList.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HandLandmark.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HandLandmarkCategory.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HandLandmarkerEventResult -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is HandLandmarkList -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is HandLandmarkCategoryList -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is HandLandmark -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is HandLandmarkCategory -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val HandLandmarkerPluginPigeonMethodCodec = StandardMethodCodec(HandLandmarkerPluginPigeonCodec())


private class HandLandmarkerPluginPigeonStreamHandler<T>(
    val wrapper: HandLandmarkerPluginPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface HandLandmarkerPluginPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/** Event channel methods for the Hand Landmarker plugin. */
abstract class HandLandmarkerEventStreamStreamHandler : HandLandmarkerPluginPigeonEventChannelWrapper<HandLandmarkerEventResult> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: HandLandmarkerEventStreamStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.hand_landmarker.HandLandmarkerEventChannel.handLandmarkerEventStream"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = HandLandmarkerPluginPigeonStreamHandler<HandLandmarkerEventResult>(streamHandler)
      EventChannel(messenger, channelName, HandLandmarkerPluginPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from HandLandmarkerPluginPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<HandLandmarkerEventResult>) {}

override fun onCancel(p0: Any?) {}
}
      
