// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class HandLandmarkerEventResult {
  HandLandmarkerEventResult({
    required this.timestampMs,
    required this.landmarks,
    required this.worldLandmarks,
    required this.handedness,
  });

  int timestampMs;

  List<HandLandmarkList> landmarks;

  List<HandLandmarkList> worldLandmarks;

  List<HandLandmarkCategoryList> handedness;

  List<Object?> _toList() {
    return <Object?>[
      timestampMs,
      landmarks,
      worldLandmarks,
      handedness,
    ];
  }

  Object encode() {
    return _toList();  }

  static HandLandmarkerEventResult decode(Object result) {
    result as List<Object?>;
    return HandLandmarkerEventResult(
      timestampMs: result[0]! as int,
      landmarks: (result[1]! as List<Object?>).cast<HandLandmarkList>(),
      worldLandmarks: (result[2]! as List<Object?>).cast<HandLandmarkList>(),
      handedness: (result[3]! as List<Object?>).cast<HandLandmarkCategoryList>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HandLandmarkerEventResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class HandLandmarkList {
  HandLandmarkList({
    required this.data,
  });

  List<HandLandmark> data;

  List<Object?> _toList() {
    return <Object?>[
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static HandLandmarkList decode(Object result) {
    result as List<Object?>;
    return HandLandmarkList(
      data: (result[0]! as List<Object?>).cast<HandLandmark>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HandLandmarkList || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class HandLandmarkCategoryList {
  HandLandmarkCategoryList({
    required this.data,
  });

  List<HandLandmarkCategory> data;

  List<Object?> _toList() {
    return <Object?>[
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static HandLandmarkCategoryList decode(Object result) {
    result as List<Object?>;
    return HandLandmarkCategoryList(
      data: (result[0]! as List<Object?>).cast<HandLandmarkCategory>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HandLandmarkCategoryList || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class HandLandmark {
  HandLandmark({
    required this.x,
    required this.y,
    required this.z,
    this.visibility,
    this.presence,
  });

  double x;

  double y;

  double z;

  double? visibility;

  double? presence;

  List<Object?> _toList() {
    return <Object?>[
      x,
      y,
      z,
      visibility,
      presence,
    ];
  }

  Object encode() {
    return _toList();  }

  static HandLandmark decode(Object result) {
    result as List<Object?>;
    return HandLandmark(
      x: result[0]! as double,
      y: result[1]! as double,
      z: result[2]! as double,
      visibility: result[3] as double?,
      presence: result[4] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HandLandmark || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class HandLandmarkCategory {
  HandLandmarkCategory({
    required this.score,
    required this.index,
    required this.categoryName,
    required this.displayName,
  });

  double score;

  int index;

  String categoryName;

  String displayName;

  List<Object?> _toList() {
    return <Object?>[
      score,
      index,
      categoryName,
      displayName,
    ];
  }

  Object encode() {
    return _toList();  }

  static HandLandmarkCategory decode(Object result) {
    result as List<Object?>;
    return HandLandmarkCategory(
      score: result[0]! as double,
      index: result[1]! as int,
      categoryName: result[2]! as String,
      displayName: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HandLandmarkCategory || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is HandLandmarkerEventResult) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is HandLandmarkList) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is HandLandmarkCategoryList) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is HandLandmark) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is HandLandmarkCategory) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return HandLandmarkerEventResult.decode(readValue(buffer)!);
      case 130:
        return HandLandmarkList.decode(readValue(buffer)!);
      case 131:
        return HandLandmarkCategoryList.decode(readValue(buffer)!);
      case 132:
        return HandLandmark.decode(readValue(buffer)!);
      case 133:
        return HandLandmarkCategory.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Event channel methods for the Hand Landmarker plugin.
Stream<HandLandmarkerEventResult> handLandmarkerEventStream( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel handLandmarkerEventStreamChannel =
      EventChannel('dev.flutter.pigeon.hand_landmarker.HandLandmarkerEventChannel.handLandmarkerEventStream$instanceName', pigeonMethodCodec);
  return handLandmarkerEventStreamChannel.receiveBroadcastStream().map((dynamic event) {
    return event as HandLandmarkerEventResult;
  });
}
    
